wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.15.0
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1682284948.912658
    t:
      1:
      - 1
      - 41
      - 48
      - 54
      - 55
      2:
      - 1
      - 41
      - 48
      - 54
      - 55
      3:
      - 2
      - 23
      4: 3.10.11
      5: 0.15.0
      8:
      - 1
      - 5
