wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.15.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1689670806.518847
    t:
      1:
      - 1
      - 41
      - 48
      - 55
      2:
      - 1
      - 41
      - 48
      - 55
      3:
      - 13
      - 23
      4: 3.11.4
      5: 0.15.5
      8:
      - 5
